git mv -- ./README.md ./readme.md
git mv -- ./99-archive/college/thesis/Youtube_data_extraction.md ./99-archive/college/thesis/youtube_data_extraction.md
git mv -- ./99-archive/college/semesters/10/desarrollo_de_videojuegos/classes/06-3D_modeling.md ./99-archive/college/semesters/10/desarrollo_de_videojuegos/classes/06-3d_modeling.md
git mv -- ./99-archive/college/semesters/09/proyecto_integrador_II/homework/04-Roboflow.md ./99-archive/college/semesters/09/proyecto_integrador_II/homework/04-roboflow.md
git mv -- ./99-archive/college/semesters/09/proyecto_integrador_II/homework/03-Play_HT.md ./99-archive/college/semesters/09/proyecto_integrador_II/homework/03-play_ht.md
git mv -- ./99-archive/college/semesters/09/proyecto_integrador_II/homework/01-GitHub_Copilot_presentation.md ./99-archive/college/semesters/09/proyecto_integrador_II/homework/01-github_copilot_presentation.md
git mv -- ./99-archive/college/semesters/09/proyecto_integrador_II/classes/02-AI_enhanced_software_engineering.md ./99-archive/college/semesters/09/proyecto_integrador_II/classes/02-ai_enhanced_software_engineering.md
git mv -- ./99-archive/college/semesters/09/proyecto_integrador_II ./99-archive/college/semesters/09/proyecto_integrador_ii
git mv -- ./99-archive/college/semesters/09/introduccion_a_la_gestion_de_proyectos_de_software/homework/02-Gemelos_GMS_database_model.md ./99-archive/college/semesters/09/introduccion_a_la_gestion_de_proyectos_de_software/homework/02-gemelos_gms_database_model.md
git mv -- ./99-archive/college/semesters/09/introduccion_a_la_gestion_de_proyectos_de_software/homework/01-Gemelos_GMS.md ./99-archive/college/semesters/09/introduccion_a_la_gestion_de_proyectos_de_software/homework/01-gemelos_gms.md
git mv -- ./99-archive/college/semesters/09/diseño_de_contenido_de_interfaces_de_usuario/homework/02-SENA_style_guide.md ./99-archive/college/semesters/09/diseño_de_contenido_de_interfaces_de_usuario/homework/02-sena_style_guide.md
git mv -- ./99-archive/college/semesters/09/diseño_de_contenido_de_interfaces_de_usuario/homework/01-SENA_app_analysis.md ./99-archive/college/semesters/09/diseño_de_contenido_de_interfaces_de_usuario/homework/01-sena_app_analysis.md
git mv -- ./99-archive/college/semesters/09/ciberseguridad/homework/01-IP_routing.md ./99-archive/college/semesters/09/ciberseguridad/homework/01-ip_routing.md
git mv -- ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/03-NP-completeness/02-SAT_and_3-SAT.md ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/03-NP-completeness/02-sat_and_3-sat.md
git mv -- ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/03-NP-completeness ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/03-np-completeness
git mv -- ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/02-discrete_optimization/05-Simplex.md ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/02-discrete_optimization/05-simplex.md
git mv -- ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/01-dynamic_and_greedy_programming/02-introduction_to_dynamic_programming-Fibonacci_sequence.md ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II/classes/01-dynamic_and_greedy_programming/02-introduction_to_dynamic_programming-fibonacci_sequence.md
git mv -- ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_II ./99-archive/college/semesters/09/analisis_y_diseño_de_algoritmos_ii
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/homework/03-Taylor_series.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/homework/03-taylor_series.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/12-Splines.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/12-splines.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/10-Gauss-Seidel_method.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/10-gauss-seidel_method.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/09-Jacobi_method.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/09-jacobi_method.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/06-Bairstows_method.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/06-bairstows_method.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/04-Newton_Raphson_on_nonlinear_functions.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/04-newton_raphson_on_nonlinear_functions.md
git mv -- ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/03-Newton_Raphson_method.md ./99-archive/college/semesters/08/simulacion_y_computacion_numerica/classes/03-newton_raphson_method.md
git mv -- ./99-archive/college/semesters/08/introduccion_a_la_ciencia_de_datos/assets/08_01-K-means_algorithm.svg ./99-archive/college/semesters/08/introduccion_a_la_ciencia_de_datos/assets/08_01-k-means_algorithm.svg
git mv -- ./99-archive/college/semesters/08/introduccion_a_la_ciencia_de_datos/assets/01_02-CRISP-DM_diagram.png ./99-archive/college/semesters/08/introduccion_a_la_ciencia_de_datos/assets/01_02-crisp-dm_diagram.png
git mv -- ./99-archive/college/semesters/08/desarrollo_de_aplicaciones_para_dispositivos_moviles/02-UI_and_UX.md ./99-archive/college/semesters/08/desarrollo_de_aplicaciones_para_dispositivos_moviles/02-ui_and_ux.md
git mv -- ./99-archive/college/semesters/01/calculo_I ./99-archive/college/semesters/01/calculo_i
git mv -- ./99-archive/college/semesters/01/assets/calculo_I ./99-archive/college/semesters/01/assets/calculo_i
git mv -- ./99-archive/college/ASES/Sara ./99-archive/college/ASES/sara
git mv -- ./99-archive/college/ASES/Manuela ./99-archive/college/ASES/manuela
git mv -- ./99-archive/college/ASES/Juan/01-GitFlow_practice.md ./99-archive/college/ASES/Juan/01-gitflow_practice.md
git mv -- ./99-archive/college/ASES/Juan ./99-archive/college/ASES/juan
git mv -- ./99-archive/college/ASES/Jairo ./99-archive/college/ASES/jairo
git mv -- ./99-archive/college/ASES/Hector/matematicas_discretas_I ./99-archive/college/ASES/Hector/matematicas_discretas_i
git mv -- ./99-archive/college/ASES/Hector ./99-archive/college/ASES/hector
git mv -- ./99-archive/college/ASES/Grosman ./99-archive/college/ASES/grosman
git mv -- ./99-archive/college/ASES/Gabriela/03-Linux_applications_installation.md ./99-archive/college/ASES/Gabriela/03-linux_applications_installation.md
git mv -- ./99-archive/college/ASES/Gabriela/02-how_to_format_code_in_LaTeX.md ./99-archive/college/ASES/Gabriela/02-how_to_format_code_in_latex.md
git mv -- ./99-archive/college/ASES/Gabriela/01-Scala_setup_for_VS_Code.md ./99-archive/college/ASES/Gabriela/01-scala_setup_for_vs_code.md
git mv -- ./99-archive/college/ASES/Gabriela ./99-archive/college/ASES/gabriela
git mv -- ./99-archive/college/ASES/Esteban/02-suggested_solution_for_Sum_of_Multiples_problem.md ./99-archive/college/ASES/Esteban/02-suggested_solution_for_sum_of_multiples_problem.md
git mv -- ./99-archive/college/ASES/Esteban ./99-archive/college/ASES/esteban
git mv -- ./99-archive/college/ASES ./99-archive/college/ases
git mv -- ./02-resources/courses/Python_Django_full_course_for_beginners.md ./02-resources/courses/python_django_full_course_for_beginners.md
git mv -- ./02-resources/courses/Linux_para_principiantes.md ./02-resources/courses/linux_para_principiantes.md
git mv -- ./02-resources/courses/Kubernetes.md ./02-resources/courses/kubernetes.md
git mv -- ./02-resources/courses/introduccion_a_Linux/02-scripting_en_Bash.md ./02-resources/courses/introduccion_a_Linux/02-scripting_en_bash.md
git mv -- ./02-resources/courses/introduccion_a_Linux ./02-resources/courses/introduccion_a_linux
git mv -- ./02-resources/courses/introduccion_al_Hacking ./02-resources/courses/introduccion_al_hacking
git mv -- ./02-resources/courses/HTML5_desde_cero.md ./02-resources/courses/html5_desde_cero.md
git mv -- ./02-resources/courses/HCIA-Datacom/assets/02_03-TCP_and_UDP_header_formats.jpg ./02-resources/courses/HCIA-Datacom/assets/02_03-tcp_and_udp_header_formats.jpg
git mv -- ./02-resources/courses/HCIA-Datacom/assets/02_02-common_TCP_IP_protocols.jpg ./02-resources/courses/HCIA-Datacom/assets/02_02-common_tcp_ip_protocols.jpg
git mv -- ./02-resources/courses/HCIA-Datacom/assets/02_01-TCP_IP_reference_model.jpg ./02-resources/courses/HCIA-Datacom/assets/02_01-tcp_ip_reference_model.jpg
git mv -- ./02-resources/courses/HCIA-Datacom ./02-resources/courses/hcia-datacom
git mv -- ./02-resources/courses/curso_de_Prisma_ORM.md ./02-resources/courses/curso_de_prisma_orm.md
git mv -- ./02-resources/courses/building_web_applications_in_Java_with_Spring_Boot_3.md ./02-resources/courses/building_web_applications_in_java_with_spring_boot_3.md
git mv -- ./02-resources/courses/AWS_cloud_practitioner_essentials ./02-resources/courses/aws_cloud_practitioner_essentials
git mv -- ./02-resources/courses/assets/courses/introduccion_a_Linux/01_01-Linux_directory_structure.png ./02-resources/courses/assets/courses/introduccion_a_Linux/01_01-linux_directory_structure.png
git mv -- ./02-resources/courses/assets/courses/introduccion_a_Linux ./02-resources/courses/assets/courses/introduccion_a_linux
git mv -- ./02-resources/courses/aprende_Git_y_GitHub.md ./02-resources/courses/aprende_git_y_github.md
git mv -- ./02-resources/courses/aprende_Docker_ahora.md ./02-resources/courses/aprende_docker_ahora.md
git mv -- ./02-resources/courses/aprende_a_programar_con_Processing.md ./02-resources/courses/aprende_a_programar_con_processing.md
git mv -- ./02-resources/courses/20_things_javascript_developers_should_know_but_probably_do_not/01-inheritance_in_JavaScript-prototypal_inheritance_tutorial.md ./02-resources/courses/20_things_javascript_developers_should_know_but_probably_do_not/01-inheritance_in_javascript-prototypal_inheritance_tutorial.md
git mv -- ./02-resources/books/the_Linux_command_line/02-learning_the_Shell ./02-resources/books/the_Linux_command_line/02-learning_the_shell
git mv -- ./02-resources/books/the_Linux_command_line ./02-resources/books/the_linux_command_line
git mv -- ./02-resources/books/eloquent_JavaScript/14-JavaScript_and_the_browser.md ./02-resources/books/eloquent_JavaScript/14-javascript_and_the_browser.md
git mv -- ./02-resources/books/eloquent_JavaScript ./02-resources/books/eloquent_javascript
git mv -- ./01-areas/systems_engineering/web/WSGI.md ./01-areas/systems_engineering/web/wsgi.md
git mv -- ./01-areas/systems_engineering/web/WebSocket.md ./01-areas/systems_engineering/web/websocket.md
git mv -- ./01-areas/systems_engineering/web/SOAP.md ./01-areas/systems_engineering/web/soap.md
git mv -- ./01-areas/systems_engineering/web/REST.md ./01-areas/systems_engineering/web/rest.md
git mv -- ./01-areas/systems_engineering/web/REST_API.md ./01-areas/systems_engineering/web/rest_api.md
git mv -- ./01-areas/systems_engineering/web/gRPC.md ./01-areas/systems_engineering/web/grpc.md
git mv -- ./01-areas/systems_engineering/web/GraphQL.md ./01-areas/systems_engineering/web/graphql.md
git mv -- ./01-areas/systems_engineering/web/Django.md ./01-areas/systems_engineering/web/django.md
git mv -- ./01-areas/systems_engineering/web/ASGI.md ./01-areas/systems_engineering/web/asgi.md
git mv -- ./01-areas/systems_engineering/programming_languages/Python/RegEx.md ./01-areas/systems_engineering/programming_languages/Python/regex.md
git mv -- ./01-areas/systems_engineering/programming_languages/Python/Pickle.md ./01-areas/systems_engineering/programming_languages/Python/pickle.md
git mv -- ./01-areas/systems_engineering/programming_languages/Python ./01-areas/systems_engineering/programming_languages/python
git mv -- ./01-areas/systems_engineering/programming_languages/C_sharp/collections_and_LINQ.md ./01-areas/systems_engineering/programming_languages/C_sharp/collections_and_linq.md
git mv -- ./01-areas/systems_engineering/programming_languages/C_sharp ./01-areas/systems_engineering/programming_languages/c_sharp
git mv -- ./01-areas/systems_engineering/programming_languages/C_plus_plus ./01-areas/systems_engineering/programming_languages/c_plus_plus
git mv -- ./01-areas/systems_engineering/problems/SAT.md ./01-areas/systems_engineering/problems/sat.md
git mv -- ./01-areas/systems_engineering/problems/Fibonacci_sequence.md ./01-areas/systems_engineering/problems/fibonacci_sequence.md
git mv -- ./01-areas/systems_engineering/Linux ./01-areas/systems_engineering/linux
git mv -- ./01-areas/systems_engineering/LaTeX_cheatsheet.md ./01-areas/systems_engineering/latex_cheatsheet.md
git mv -- ./01-areas/systems_engineering/Kubernetes.md ./01-areas/systems_engineering/kubernetes.md
git mv -- ./01-areas/systems_engineering/fundamentals/SOLID_principles.md ./01-areas/systems_engineering/fundamentals/solid_principles.md
git mv -- ./01-areas/systems_engineering/fundamentals/Git_and_Github/GitFlow.md ./01-areas/systems_engineering/fundamentals/Git_and_Github/gitflow.md
git mv -- ./01-areas/systems_engineering/fundamentals/Git_and_Github ./01-areas/systems_engineering/fundamentals/git_and_github
git mv -- ./01-areas/systems_engineering/fundamentals/algorithms/Dijkstra.md ./01-areas/systems_engineering/fundamentals/algorithms/dijkstra.md
git mv -- ./01-areas/systems_engineering/data/5Vs_of_big_data.md ./01-areas/systems_engineering/data/5vs_of_big_data.md
git mv -- ./01-areas/systems_engineering/Class_Diagram-Mermaid.md ./01-areas/systems_engineering/class_diagram-mermaid.md
git mv -- ./01-areas/systems_engineering/AI ./01-areas/systems_engineering/ai
git mv -- ./01-areas/statistics/Bayes_theorem.md ./01-areas/statistics/bayes_theorem.md
git mv -- ./01-areas/math/Taylor_series.md ./01-areas/math/taylor_series.md
git mv -- ./01-areas/math/LaTeX_cheatsheet.md ./01-areas/math/latex_cheatsheet.md
git mv -- ./01-areas/math/007-Newton_Raphson_method.md ./01-areas/math/007-newton_raphson_method.md
git mv -- ./01-areas/Duolingo ./01-areas/duolingo
git mv -- ./00-inbox/to_do/EditorConfig.md ./00-inbox/to_do/editorconfig.md
git mv -- ./00-inbox/SST_data_dictionary.md ./00-inbox/sst_data_dictionary.md
git mv -- ./00-inbox/random/Fortnite_controls.md ./00-inbox/random/fortnite_controls.md
git mv -- ./00-inbox/random/Cyberpunk_2077_controls.md ./00-inbox/random/cyberpunk_2077_controls.md
git mv -- ./00-inbox/GitLab_configuration.md ./00-inbox/gitlab_configuration.md
